cellIdPreamble: "cell-"

cells:
  ethernet 1/1/1:  { dataRef: "ethernet 1/1/1",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/2:  { dataRef: "ethernet 1/1/2",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/3:  { dataRef: "ethernet 1/1/3",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/4:  { dataRef: "ethernet 1/1/4",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/5:  { dataRef: "ethernet 1/1/5",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/6:  { dataRef: "ethernet 1/1/6",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/7:  { dataRef: "ethernet 1/1/7",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/8:  { dataRef: "ethernet 1/1/8",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/9:  { dataRef: "ethernet 1/1/9",  cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/10: { dataRef: "ethernet 1/1/10", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/11: { dataRef: "ethernet 1/1/11", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/12: { dataRef: "ethernet 1/1/12", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/13: { dataRef: "ethernet 1/1/13", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/14: { dataRef: "ethernet 1/1/14", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/15: { dataRef: "ethernet 1/1/15", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/16: { dataRef: "ethernet 1/1/16", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/17: { dataRef: "ethernet 1/1/17", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/18: { dataRef: "ethernet 1/1/18", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/19: { dataRef: "ethernet 1/1/19", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/20: { dataRef: "ethernet 1/1/20", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/21: { dataRef: "ethernet 1/1/21", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/22: { dataRef: "ethernet 1/1/22", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/23: { dataRef: "ethernet 1/1/23", cellColor: { thresholdsRef: operstatus } }
  ethernet 1/1/24: { dataRef: "ethernet 1/1/24", cellColor: { thresholdsRef: operstatus } }