cellIdPreamble: "cell-"

cells:
  port1:
    dataRef: port1
    cellColor:
      thresholdsRef: operstatus

  port2:
    dataRef: port2
    cellColor:
      thresholdsRef: operstatus

  port3:
    dataRef: port3
    cellColor:
      thresholdsRef: operstatus