rules:
  - id: port-status
    widgets: ports
    stroke:
      value: metric
      mappings:
        - when: 1
          color: "#00c853"
        - when: 2
          color: "#d50000"
      default: "#555555"