---
cellIdPreamble: "cell-"

cells:
  port1:  { dataRef: port1,  fillColor: { thresholdsRef: operstatus } }
  port2:  { dataRef: port2,  fillColor: { thresholdsRef: operstatus } }
  port3:  { dataRef: port3,  fillColor: { thresholdsRef: operstatus } }
  port4:  { dataRef: port4,  fillColor: { thresholdsRef: operstatus } }
  port5:  { dataRef: port5,  fillColor: { thresholdsRef: operstatus } }
  port6:  { dataRef: port6,  fillColor: { thresholdsRef: operstatus } }
  port7:  { dataRef: port7,  fillColor: { thresholdsRef: operstatus } }
  port8:  { dataRef: port8,  fillColor: { thresholdsRef: operstatus } }
  port9:  { dataRef: port9,  fillColor: { thresholdsRef: operstatus } }
  port10: { dataRef: port10, fillColor: { thresholdsRef: operstatus } }
  port11: { dataRef: port11, fillColor: { thresholdsRef: operstatus } }
  port12: { dataRef: port12, fillColor: { thresholdsRef: operstatus } }
  port13: { dataRef: port13, fillColor: { thresholdsRef: operstatus } }
  port14: { dataRef: port14, fillColor: { thresholdsRef: operstatus } }
  port15: { dataRef: port15, fillColor: { thresholdsRef: operstatus } }
  port16: { dataRef: port16, fillColor: { thresholdsRef: operstatus } }
  port17: { dataRef: port17, fillColor: { thresholdsRef: operstatus } }
  port18: { dataRef: port18, fillColor: { thresholdsRef: operstatus } }
  port19: { dataRef: port19, fillColor: { thresholdsRef: operstatus } }
  port20: { dataRef: port20, fillColor: { thresholdsRef: operstatus } }
  port21: { dataRef: port21, fillColor: { thresholdsRef: operstatus } }
  port22: { dataRef: port22, fillColor: { thresholdsRef: operstatus } }
  port23: { dataRef: port23, fillColor: { thresholdsRef: operstatus } }
  port24: { dataRef: port24, fillColor: { thresholdsRef: operstatus } }