---
colors:
  up: "#00c853"
  down: "#d50000"

cellColorMappings:
  darkTheme:
    up: up
    down: down
  lightTheme:
    up: up
    down: down

thresholds:
  operstatus:
    - { color: up, level: 1 }
    - { color: down, level: 2 }